name: OWASP ZAP Scan

on:
  workflow_dispatch:  

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (not strictly needed for external target)
        uses: actions/checkout@v3

      - name: Create report directory
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zap-reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t https://practicesoftwaretesting.com \
              -r zap_report.html \
              -J zap_report.json \
              -n zap-context.context \
              -d

      - name: Upload ZAP Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: zap-reports/zap_report.html

      - name: Upload ZAP Report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: zap-reports/zap_report.json
