name: OWASP ZAP Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start target app (example)
        run: |
          docker run -d -p 8080:80 --name mywebapp nginx:alpine
          sleep 10 

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-reports
          docker run --network host \
            -v ${{ github.workspace }}/zap-reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://localhost:8080 \
              -r zap_report.html \
              -J zap_report.json

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap-reports/zap_report.html

