name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: Prepare ZAP report directory
        run: mkdir -p zap-reports

      - name: Run ZAP scan
        run: |
          docker run --network host \
            -v ${{ github.workspace }}/zap-reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t https://practicesoftwaretesting.com \
              -r zap_report.html \
              -J zap_report.json

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-reports/zap_report.html
